### ISSUE TITLE
Prisma user creation errors

### ISSUE THREAD

**Issue by libkush** [ComputerSocietyVITC/Lemons#23]
Creation of users doesn't handle errors.

For example, two registrations with same regNum will create an entry in `Auth` table, but not in the `User` table. Corresponding errors are logged as shown below

<img width="958" alt="image" src="https://github.com/user-attachments/assets/5d217eb2-3881-4ccd-a3b7-8fe95a3d383e" />

**Comment by Aditya-Jyoti** [comment]
Are you working on this right now or should I push changes?

**Comment by libkush** [comment]
You can go ahead.
